# See http://pre-commit.com/#python
# See https://github.com/pre-commit/pre-commit-hooks
# Run 'pre-commit install' to install the pre-commit hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: detect-private-key
  # when we use black, comment out double-quote-string-fixer
  # - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
    exclude: (.csv|.tsv)$
  # TODO: enable pretty-format-json
  # - id: pretty-format-json
  #   args: ['--no-sort-keys', '--autofix']
  # don't commit directly to main or master
  - id: no-commit-to-branch

# See also https://adamj.eu/tech/2021/09/16/introducing-django-upgrade/
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade
      args: [ --py39-plus ]

- repo: https://github.com/myint/autoflake
  rev: v2.0.2
  hooks:
  - id: autoflake
    args:
      - --in-place
      - --remove-unused-variables
      - --remove-all-unused-imports

- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.9
    exclude: ^migrations/

# flake8 after black, so black can fix formatting first
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8


- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args:
        - --src=src,bin
        # line length must match black and flake8
        # - --profile=black

- repo: https://github.com/PyCQA/pylint
  rev: v2.17.1
  hooks:
    - id: pylint
      args:
        - --disable=consider-using-in
        - --disable=disallowed-name
        - --disable=fixme
        - --disable=import-error
        - --disable=logging-fstring-interpolation
        - --disable=missing-class-docstring
        - --disable=missing-function-docstring
        - --disable=missing-module-docstring
        - --disable=no-name-in-module
        - --disable=no-member
        - --disable=too-few-public-methods
        - --disable=too-many-instance-attributes
        - --disable=too-many-arguments
        - --disable=too-many-branches
        - --disable=too-many-locals
        - --disable=unpacking-non-sequence
        - --disable=unspecified-encoding

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.1.1
  hooks:
    - id: mypy
      additional_dependencies:
        - types-requests
      args:
        - --ignore-missing-imports

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.4.2
  hooks:
  - id: forbid-crlf
  # don't just remove, seems dangerous
  # - id: remove-crlf
  - id: forbid-tabs
    exclude: (README.md|.csv)$
  # don't just remove, seems dangerous
  # - id: remove-tabs
